compiler:
  solc:
    optimizer:
      enabled: true
      runs: 200
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0"
      - "@openzeppelin-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.6.0"
networks:
  default: development
  hardhat-fork:
    cmd_settings:
      fork_block: 14888885

reports:
  exclude_paths:
    - interfaces/**/*.*

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.6.0
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.6.0
